is_debug: true
dir:
    log: /data/logs/shop
    data: /data/shop
    cache: ./cache
    template: ./templates
db:
    host: localhost
    port: 3306
    user: shop
    password: shop
    dbname: shop
memcached:
    host: localhost
    port: 11211
aws:
    profile: shop
    region: cn-north-1
dynamodb:
    prefix: shop-
